### ISSUE TITLE
On search page but no disable-search button

### ISSUE THREAD

**Issue by dhowe** [dhowe/ChinaEye#59] opened 2017-03-27 11:10 UTC
![image](https://cloud.githubusercontent.com/assets/737638/24353640/10b3a678-1321-11e7-9937-8e8a49133ce8.png)

are we checking the location of the current tab _every_ time the menu is opened?

**Comment by cqx931** [comment] 2017-03-27 11:40
Every time the menu is open, it is getting the current tab id/url and try to find the blocking status of the current tag.
Both this issue and https://github.com/dhowe/ChinaEye/issues/58 are caused by clicking recheck on blocked pages that are blocked by keyword and allowed by the servers.

The current way of setting getBlockStatus will overwrite all the information and since recheck button only checks the server, it will update the blockStatus to allow, which disables the whitelist buttons.

**Comment by dhowe** [comment] 2017-03-27 11:45
This is pretty confusing -- do you have a solution in mind? 

1. Seems that even if you click 'recheck now', your settings should persist.
2. On the case where the page/search is **not** disabled, the interface should look the same as if you had visited the page for the first time (no cache, etc.).

**Comment by cqx931** [comment] 2017-03-28 04:17
A quick and easy solution would be to call checkPage instead of checkServer when clicking "recheck now" button.
Though it actually recheck everything instead of just the server. 

A more proper fix would be to pass trigger(either from check search keyword or from existing BlockingStatus) to checkServer, and if trigger != undefined, status is block.

**Comment by cqx931** [comment] 2017-03-28 08:32
This should be fixed in the latest PR: https://github.com/dhowe/ChinaEye/pull/63, please check.

**Closed as completed** 2017-04-13 07:37 UTC
Labels: priority: Med
